### ISSUE TITLE
Adding support for DE0-Nano?

### ISSUE THREAD

**Issue by 0xff7** [fupy/issues-wiki#10]
So I've ordered a Mimas v2 so I can start messing with the FuPy project but since I've already got a DE0-Nano I was wondering if adding support for it is possible? Or is FuPy something that will only run on Xilinx based FPGA's?  I'd be willing to attempt adding support for it myself if someone could confirm it would likely work and think it could be a nice way to familiarize myself a bit more with FPGA's in general since I'm still new to them

**Comment by 0xff7** [comment]
Figured this would be a better suited question for https://github.com/fupy/micropython so decided to close it. Here's a link https://github.com/fupy/micropython/issues/55#issue-403023635

**Comment by ewenmcneill** [comment]
FTR, the "`issues-wiki`" repo is pretty much intended for FuPy-wide issues like this, so it was a fine place to ask.  I've answered the question on the other ticket (https://github.com/fupy/micropython/issues/55#issuecomment-457971268), but will also include it below in case someone else finds this and wants to know the answer.

@0xff7 So far FuPy has been made to work on some Xilinx (Spartan 6 / Artix 7) and some Lattice (iCE 40 / iCE 40 UP) boards.  Most of the porting work is in https://github.com/timvideos/litex-buildenv/ to get things building/uploading to the board, with just a bit of tweaking around serial console / IRQ handling needed in `ports/fupy`.  

It looks like the [DE0-Nano](https://www.terasic.com.tw/cgi-bin/page/archive.pl?No=593) is an [Altera Cyclone IV based board](https://www.terasic.com.tw/cgi-bin/page/archive.pl?Language=English&CategoryNo=165&No=593&PartNo=2#section) that is probably big enough to work.  But so far no one has done any work getting https://github.com/timvideos/litex-buildenv/ to build things using the Altera tool chain, so that'd probably be the piece needing the most work.

I'd suggest getting familiar with the build/upload process on the Mimas v2 first, and then maybe considering if you're the one to figure out how to hook up `litex-buildenv` to all the various Altera tools.  You'll certainly learn a lot about how everything fits together attempting to port it to a new board!  (The `#timvideos` IRC channel, on Freenode, is the best place to ask for interactive assistance; but note that the people there are also most familiar with the Xilinx / Lattice tool chains.)

Ewen
